# Generated by Django 2.2 on 2020-01-09 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aut_name', models.CharField(max_length=20)),
                ('Aut_country', models.CharField(max_length=20)),
                ('Aut_Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='BLOG_Table1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('contain', models.TextField()),
                ('Date', models.DateTimeField()),
                ('publish', models.CharField(choices=[('PB', 'Public'), ('PV', 'Private')], default='Private', max_length=20)),
                ('author_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BLOGAPP.Author_Details')),
            ],
        ),
    ]
