# Generated by Django 2.2 on 2020-01-10 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLOGAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_table1',
            name='author_name',
            field=models.CharField(max_length=20),
        ),
    ]
