# Generated by Django 2.2 on 2020-01-10 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BLOGAPP', '0002_auto_20200110_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_table1',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='blog_table1',
            name='publish',
        ),
    ]
