# Generated by Django 2.2 on 2020-01-28 06:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BLOGAPP', '0005_blog_table1_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_table1',
            name='author_name',
        ),
        migrations.AddField(
            model_name='blog_table1',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog_table1',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 28, 11, 30, 22, 367445), null=True),
        ),
    ]
